//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wazzifni.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wazzifni.Localization.SourceFiles.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute data type does not match input.
        /// </summary>
        public static string AttributeDataTypeDoesnotMatchInput {
            get {
                return ResourceManager.GetString("AttributeDataTypeDoesnotMatchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attribute value has previous value.
        /// </summary>
        public static string AttributeValueIsAlreadyExist {
            get {
                return ResourceManager.GetString("AttributeValueIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This broker cannot be restored because its contact numbers have been permanently deleted..
        /// </summary>
        public static string BrokerContactEmptyForRecoverBrokerUser {
            get {
                return ResourceManager.GetString("BrokerContactEmptyForRecoverBrokerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Is Not In Approve Status Please Wait  for admin approval.
        /// </summary>
        public static string BrokerIsNotApprove {
            get {
                return ResourceManager.GetString("BrokerIsNotApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete because there are reservations under processing. Please close the reservation status and try again later.
        /// </summary>
        public static string CannotDeleteDueToReservationsUndeProcessing {
            get {
                return ResourceManager.GetString("CannotDeleteDueToReservationsUndeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit some information for this property due to existing or future confirmed reservations..
        /// </summary>
        public static string CannotUpdateThisPropertyDueToReservations {
            get {
                return ResourceManager.GetString("CannotUpdateThisPropertyDueToReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this request because it is in a {0} state..
        /// </summary>
        public static string CantDeleteThisRequestNotClosed {
            get {
                return ResourceManager.GetString("CantDeleteThisRequestNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contribution already exists for the specified tower..
        /// </summary>
        public static string ContributionExist {
            get {
                return ResourceManager.GetString("ContributionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Exceeds Max File Size.
        /// </summary>
        public static string FileSizeExceedsMaxFileSize {
            get {
                return ResourceManager.GetString("FileSizeExceedsMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Supported In MegaByte.
        /// </summary>
        public static string FileSizeSupported {
            get {
                return ResourceManager.GetString("FileSizeSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Value.
        /// </summary>
        public static string IncompatibleValue {
            get {
                return ResourceManager.GetString("IncompatibleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deadline for confirming your reservation must be specified in hours and minutes.
        /// </summary>
        public static string InvalidDedlineToConfirmReservation {
            get {
                return ResourceManager.GetString("InvalidDedlineToConfirmReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Need to Login First.
        /// </summary>
        public static string LogInFirst {
            get {
                return ResourceManager.GetString("LogInFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Video has a Very Low Quality. Try to Upload another Video with better Quality..
        /// </summary>
        public static string LowResolutionVideo {
            get {
                return ResourceManager.GetString("LowResolutionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no reservation feature with this category.
        /// </summary>
        public static string NoReservationFeatureWithThisCategory {
            get {
                return ResourceManager.GetString("NoReservationFeatureWithThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no reservation feature with this property.
        /// </summary>
        public static string NoReservationFeatureWithThisProperty {
            get {
                return ResourceManager.GetString("NoReservationFeatureWithThisProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant be deactivate It has related {0}.
        /// </summary>
        public static string ObjectCantBeDeactivate {
            get {
                return ResourceManager.GetString("ObjectCantBeDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant be delete it has related {0}.
        /// </summary>
        public static string ObjectCantBeDelete {
            get {
                return ResourceManager.GetString("ObjectCantBeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Already Exist.
        /// </summary>
        public static string ObjectIsAlreadyExist {
            get {
                return ResourceManager.GetString("ObjectIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Found.
        /// </summary>
        public static string ObjectWasNotFound {
            get {
                return ResourceManager.GetString("ObjectWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Is Not For Rent.
        /// </summary>
        public static string PropertyIsNotForRent {
            get {
                return ResourceManager.GetString("PropertyIsNotForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number allowed..
        /// </summary>
        public static string ReachedMaximumNumberAllowed {
            get {
                return ResourceManager.GetString("ReachedMaximumNumberAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation includes dates that are beyond the allowed last date for reservations..
        /// </summary>
        public static string ReservationDatesBeyondAllowedLastDate {
            get {
                return ResourceManager.GetString("ReservationDatesBeyondAllowedLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation includes other reservation dates that are still under processing.
        /// </summary>
        public static string ReservationIncludesAnotherReservationDates {
            get {
                return ResourceManager.GetString("ReservationIncludesAnotherReservationDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation includes dates that are in the past or today, which are not allowed..
        /// </summary>
        public static string ReservationIncludesPastOrCurrentDate {
            get {
                return ResourceManager.GetString("ReservationIncludesPastOrCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation includes dates that are not available for booking..
        /// </summary>
        public static string ReservationIncludesUnavailableDates {
            get {
                return ResourceManager.GetString("ReservationIncludesUnavailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signingup information not correct.
        /// </summary>
        public static string SignUpNotComplete {
            get {
                return ResourceManager.GetString("SignUpNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attached File Type Is Not Acceptable.
        /// </summary>
        public static string TheAttachedFileTypeIsNotAcceptable {
            get {
                return ResourceManager.GetString("TheAttachedFileTypeIsNotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is already in use.
        /// </summary>
        public static string ThePhoneNumberIsAlreadyInUse {
            get {
                return ResourceManager.GetString("ThePhoneNumberIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has not selected a service provider.
        /// </summary>
        public static string TheRequestHasNotSelectedAServiceProvider {
            get {
                return ResourceManager.GetString("TheRequestHasNotSelectedAServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Position Is Already Exist.
        /// </summary>
        public static string ThisPositionIsAlreadyExist {
            get {
                return ResourceManager.GetString("ThisPositionIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The broker has exhausted his publishing balance or does not have a bundle.
        /// </summary>
        public static string UserCanotPuplish {
            get {
                return ResourceManager.GetString("UserCanotPuplish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the user cannot be retrieved because there is an existing user with the same username..
        /// </summary>
        public static string UserNameTakenForRecoverBrokerUser {
            get {
                return ResourceManager.GetString("UserNameTakenForRecoverBrokerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found. Please create an account with your phone number..
        /// </summary>
        public static string UserNotFoundPleasCreateNewAccount {
            get {
                return ResourceManager.GetString("UserNotFoundPleasCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is expired..
        /// </summary>
        public static string VerificationCodeIsExpired {
            get {
                return ResourceManager.GetString("VerificationCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code isn&apos;t correct.
        /// </summary>
        public static string VerificationCodeIsnotCorrect {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code Isn&apos;t valid.
        /// </summary>
        public static string VerificationCodeIsnotValid {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Video Can Not be Attached to more than {0} Tags.
        /// </summary>
        public static string VideoTagsNumberIsAboveMaximum {
            get {
                return ResourceManager.GetString("VideoTagsNumberIsAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Number is Positive.
        /// </summary>
        public static string VideoTagsNumberIsPositive {
            get {
                return ResourceManager.GetString("VideoTagsNumberIsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t  do this action.
        /// </summary>
        public static string YouCannotDoThisAction {
            get {
                return ResourceManager.GetString("YouCannotDoThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exhausted the specified number of publishing possibilities.
        /// </summary>
        public static string YouCannotDoThisAnymore {
            get {
                return ResourceManager.GetString("YouCannotDoThisAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the number of posts allowed. You currently have a number of posts under review, in addition to the number of posts you have published. Please wait for your current posts to be reviewed before publishing more..
        /// </summary>
        public static string YouCannotDoThisAnymoreWithPostsChecking {
            get {
                return ResourceManager.GetString("YouCannotDoThisAnymoreWithPostsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number is not verified.
        /// </summary>
        public static string YourPhoneNumberIsntVerified {
            get {
                return ResourceManager.GetString("YourPhoneNumberIsntVerified", resourceCulture);
            }
        }
    }
}
