//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wazzifni.Localization.SourceFiles {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tokens
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tokens()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wazzifni.Localization.SourceFiles.Tokens", typeof(Tokens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin
        {
            get
            {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Slider Image.
        /// </summary>
        public static string Advertisiment
        {
            get
            {
                return ResourceManager.GetString("Advertisiment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment
        {
            get
            {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute
        {
            get
            {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute choice.
        /// </summary>
        public static string AttributeChoice
        {
            get
            {
                return ResourceManager.GetString("AttributeChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basic user .
        /// </summary>
        public static string BasicUser
        {
            get
            {
                return ResourceManager.GetString("BasicUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BrokerUser.
        /// </summary>
        public static string BrokerUser
        {
            get
            {
                return ResourceManager.GetString("BrokerUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        public static string Bundle
        {
            get
            {
                return ResourceManager.GetString("Bundle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car
        {
            get
            {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Car category.
        /// </summary>
        public static string CarCategory
        {
            get
            {
                return ResourceManager.GetString("CarCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category type.
        /// </summary>
        public static string CategoryType
        {
            get
            {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Characteristic.
        /// </summary>
        public static string Characteristic
        {
            get
            {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color
        {
            get
            {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string Complaint
        {
            get
            {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complaint Category.
        /// </summary>
        public static string ComplaintCategory
        {
            get
            {
                return ResourceManager.GetString("ComplaintCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        public static string Compound
        {
            get
            {
                return ResourceManager.GetString("Compound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail
        {
            get
            {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Phone Number.
        /// </summary>
        public static string ConfirmPhoneNumber
        {
            get
            {
                return ResourceManager.GetString("ConfirmPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ContactUsRequest.
        /// </summary>
        public static string ContactUsRequest
        {
            get
            {
                return ResourceManager.GetString("ContactUsRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East
        {
            get
            {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress
        {
            get
            {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string Facility
        {
            get
            {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgetPassword
        {
            get
            {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        public static string ForRent
        {
            get
            {
                return ResourceManager.GetString("ForRent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        public static string ForSale
        {
            get
            {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Four or more.
        /// </summary>
        public static string FourOrMore
        {
            get
            {
                return ResourceManager.GetString("FourOrMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frequently Question.
        /// </summary>
        public static string FrequentlyQuestion
        {
            get
            {
                return ResourceManager.GetString("FrequentlyQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Furnished.
        /// </summary>
        public static string Furnished
        {
            get
            {
                return ResourceManager.GetString("Furnished", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Good condition.
        /// </summary>
        public static string GoodCondition
        {
            get
            {
                return ResourceManager.GetString("GoodCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotel apartment.
        /// </summary>
        public static string HotelApartment
        {
            get
            {
                return ResourceManager.GetString("HotelApartment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly
        {
            get
            {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National Number.
        /// </summary>
        public static string NationalNumber
        {
            get
            {
                return ResourceManager.GetString("NationalNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Needs renovation.
        /// </summary>
        public static string NeedsRenovation
        {
            get
            {
                return ResourceManager.GetString("NeedsRenovation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New home.
        /// </summary>
        public static string NewHome
        {
            get
            {
                return ResourceManager.GetString("NewHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Bundle Description Was Provided.
        /// </summary>
        public static string NoBundleDescriptionProvided
        {
            get
            {
                return ResourceManager.GetString("NoBundleDescriptionProvided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Bundle Name Was Provided.
        /// </summary>
        public static string NoBundleNameProvided
        {
            get
            {
                return ResourceManager.GetString("NoBundleNameProvided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North
        {
            get
            {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NorthEast.
        /// </summary>
        public static string NorthEast
        {
            get
            {
                return ResourceManager.GetString("NorthEast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NorthWest.
        /// </summary>
        public static string NorthWest
        {
            get
            {
                return ResourceManager.GetString("NorthWest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number
        {
            get
            {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer
        {
            get
            {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One
        {
            get
            {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Owner Available Time.
        /// </summary>
        public static string OwnerAvailableTime
        {
            get
            {
                return ResourceManager.GetString("OwnerAvailableTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient
        {
            get
            {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Penthouse.
        /// </summary>
        public static string Penthouse
        {
            get
            {
                return ResourceManager.GetString("Penthouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post
        {
            get
            {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post Category.
        /// </summary>
        public static string PostCategory
        {
            get
            {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premium user.
        /// </summary>
        public static string PremiumUser
        {
            get
            {
                return ResourceManager.GetString("PremiumUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy
        {
            get
            {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProgressMilestone.
        /// </summary>
        public static string ProgressMilestone
        {
            get
            {
                return ResourceManager.GetString("ProgressMilestone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property
        {
            get
            {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property category.
        /// </summary>
        public static string PropertyCategory
        {
            get
            {
                return ResourceManager.GetString("PropertyCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Push Notification.
        /// </summary>
        public static string PushNotification
        {
            get
            {
                return ResourceManager.GetString("PushNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region
        {
            get
            {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent
        {
            get
            {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequestService.
        /// </summary>
        public static string RequestService
        {
            get
            {
                return ResourceManager.GetString("RequestService", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role
        {
            get
            {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select
        {
            get
            {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell
        {
            get
            {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Semi Furnished.
        /// </summary>
        public static string SemiFurnished
        {
            get
            {
                return ResourceManager.GetString("SemiFurnished", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service
        {
            get
            {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ServiceProviderUser.
        /// </summary>
        public static string ServiceProviderUser
        {
            get
            {
                return ResourceManager.GetString("ServiceProviderUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ServiceScope.
        /// </summary>
        public static string ServiceScope
        {
            get
            {
                return ResourceManager.GetString("ServiceScope", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift
        {
            get
            {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single room in a shared house.
        /// </summary>
        public static string SingleRoomInASharedHouse
        {
            get
            {
                return ResourceManager.GetString("SingleRoomInASharedHouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South
        {
            get
            {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SouthEast.
        /// </summary>
        public static string SouthEast
        {
            get
            {
                return ResourceManager.GetString("SouthEast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SouthWest.
        /// </summary>
        public static string SouthWest
        {
            get
            {
                return ResourceManager.GetString("SouthWest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string Speciality
        {
            get
            {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string Studio
        {
            get
            {
                return ResourceManager.GetString("Studio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription
        {
            get
            {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubscriptionDocument.
        /// </summary>
        public static string SubscriptionDocument
        {
            get
            {
                return ResourceManager.GetString("SubscriptionDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubscriptionRequest.
        /// </summary>
        public static string SubscriptionRequest
        {
            get
            {
                return ResourceManager.GetString("SubscriptionRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Super delux.
        /// </summary>
        public static string SuperDelux
        {
            get
            {
                return ResourceManager.GetString("SuperDelux", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag
        {
            get
            {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TextFree.
        /// </summary>
        public static string TextFree
        {
            get
            {
                return ResourceManager.GetString("TextFree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three
        {
            get
            {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Three or more.
        /// </summary>
        public static string ThreeOrMore
        {
            get
            {
                return ResourceManager.GetString("ThreeOrMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TowerSupervisor.
        /// </summary>
        public static string TowerSupervisor
        {
            get
            {
                return ResourceManager.GetString("TowerSupervisor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Town house.
        /// </summary>
        public static string Townhouse
        {
            get
            {
                return ResourceManager.GetString("Townhouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string Two
        {
            get
            {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unfurnished.
        /// </summary>
        public static string Unfurnished
        {
            get
            {
                return ResourceManager.GetString("Unfurnished", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VideoCategory.
        /// </summary>
        public static string VideoCategory
        {
            get
            {
                return ResourceManager.GetString("VideoCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        public static string Villa
        {
            get
            {
                return ResourceManager.GetString("Villa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wanted.
        /// </summary>
        public static string Wanted
        {
            get
            {
                return ResourceManager.GetString("Wanted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly
        {
            get
            {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West
        {
            get
            {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog
        {
            get
            {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CompanyUser.
        /// </summary>
        public static string CompanyUser
        {
            get
            {
                return ResourceManager.GetString("CompanyUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trainee.
        /// </summary>
        public static string Trainee
        {
            get
            {
                return ResourceManager.GetString("Trainee", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to CourseCategory.
        /// </summary>
        public static string CourseCategory
        {
            get
            {
                return ResourceManager.GetString("CourseCategory", resourceCulture);
            }
        }
        
    }
}
